 <div class="full-width-header header-style1 home1-modifiy home12-modifiy">
    <!-- Vertical Marquee -->
    <div class="switch-theme-mode">
      <div class="marquee">
        <div class="marquee-inner" id="marqueeContent">
          <!-- Bars generated by JS -->
        </div>
      </div>
    </div>
    <!--Header Start-->
    <header id="rs-header" class="rs-header">
      <!-- Topbar Area Start -->

      <div class="topbar-area home11-topbar">
        <div class="container-fluid top-marquee">
          <div class="row">
            <div class="col-md-12">
              <div class="mobile-marquee">
                <div class="mobile-marquee-track" id="marqueeTrack">

                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Workday Certification Training</span>
                    </a>
                  </div>

                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Workday Finance Training</span>
                    </a>
                  </div>

                  <div class="mobile-marquee-item">
                    <a href="" target="_blank">
                      <span class="mobile-overlay-text">Workday HCM Functional Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Workday HCM Technical Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Workday HCM Techno Functional Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Certification Program</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Certification Program</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Admin Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Developer Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce LWC Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce QA Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Salescloud Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Service Cloud Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce CPQ Certification Training</span>
                    </a>
                  </div>
                  <div class="mobile-marquee-item">
                    <a href="#">
                      <span class="mobile-overlay-text">Salesforce Marketing Cloud Certification Training</span>
                    </a>
                  </div>


                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="container">
          <div class="row y-middle">
            <div class="col-md-5">
              <ul class="topbar-contact">
                <li>
                  <i class="flaticon-email"></i>
                  <a href="mailto:enquiry@trainerssquad.com">enquiry@trainerssquad.com</a>
                </li>
                <li>
                  <i class="fa flaticon-call"></i>
                  <a href="tel:+91 8618388161"> +91 8618388161</a>
                </li>
              </ul>
            </div>
            <div class="col-md-7 text-right">
              <ul class="toolbar-sl-share">
                <li class="btn payment-btn">
                  <a href="#" target="_blank">
                    <span>Payment</span>
                  </a>
                </li>
                <li>
                  <a href="#" target="_blank">
                    <span><i class="fab fa-facebook text-white"></i></span>
                  </a>
                </li>
                <li>
                  <a href="https://www.instagram.com/" target="_blank" class="me-2">
                    <i class="fab fa-instagram text-white"></i>
                  </a>
                </li>
                <li>
                  <a href="https://www.linkedin.com/" target="_blank" class="me-2">
                    <i class="fab fa-linkedin-in text-white"></i>
                  </a>
                </li>
                <li>
                  <a href="https://www.youtube.com/" target="_blank">
                    <i class="fab fa-youtube text-white"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- Topbar Area End -->

      <!-- Menu Start -->

      <!--Full width header Start-->
      <div class="full-width-header header-style3 modify">
        <!--Header Start-->
        <header id="rs-header" class="rs-header">
          <!-- Menu Start -->
          <div class="menu-area menu-sticky">
            <div class="logo-part hidden-md">
              <a class="light-logo" href="index.html">
                <img src="assets/images/logo3.png" alt="" />
              </a>
              <a class="small-logo" href="index.html">
                <img src="assets/images/logo3.png" alt="" />
              </a>
            </div>
            <div class="container-fluid">
              <div class="responsive-logo">
                <img src="assets/images/logo3.png" alt="" />
              </div>

              <div class="rs-menu-area">
                <div class="main-menu">
                  <div class="mobile-menu">
                    <a class="rs-menu-toggle">
                      <i class="fa fa-bars"></i>
                    </a>
                  </div>
                  <nav class="rs-menu">
                    <ul class="nav-menu">
                      <li class="menu-item-has-children single-menu">
                        <a href="index.php">Home</a>
                      </li>
                      <li class="menu-item-has-children">
                        <a href="about-us.php">About us</a>
                        <ul class="sub-menu">
                          <li><a href="#!">Admission</a></li>
                          <li><a href="#!">Jop Portal</a></li>
                          <li><a href="#!">Blog</a></li>
                        </ul>
                      </li>
                      <li class="rs-mega-menu mega-rs menu-item-has-children current-menu-item">
                        <a href="all-courses.php">Course</a>
                        <ul class="mega-menu responsive-style">
                          <li class="mega-menu-container">
                            <div class="mega-menu-innner">
                              <div class="single-megamenu">
                                <ul class="sub-menu">
                                  <li><a href="courses-details.php">Salesforce Training</a></li>
                                  <li><a href="courses-details.php">Workday Training</a></li>
                                  <li><a href="courses-details.php">AWS Training</a></li>
                                  <li><a href="courses-details.php">ServiceNow Training</a></li>

                                </ul>
                              </div>
                              <div class="single-megamenu">
                                <ul class="sub-menu last-sub-menu">
                                  <li><a href="courses-details.php">Microsoft Azure Training</a></li>
                                  <li><a href="courses-details.php">Software Testing Training</a></li>
                                  <li><a href="courses-details.php">DataBase Training</a></li>
                                  <li><a href="courses-details.php">Blockchain Training</a></li>

                                </ul>
                              </div>
                              <div class="single-megamenu">
                                <ul class="sub-menu last-sub-menu">
                                  <li><a href="courses-details.php">Data Science & AI</a></li>
                                  <li><a href="courses-details.php">Data Analytics & Power BI</a></li>
                                  <li><a href="courses-details.php">Web Development Training</a></li>
                                  <li><a href="courses-details.php">Digital Marketing Training</a></li>
                                </ul>
                              </div>
                            </div>
                          </li>
                        </ul>
                        <!-- //.mega-menu -->
                      </li>
                      <li class="menu-item-has-children single-menu">
                        <a href="training.php">Corporate training</a>
                      </li>
                      <li class="menu-item-has-children single-menu">
                        <a href="french-course.php">language</a>
                      </li>
                      <li class="menu-item-has-children single-menu">
                        <a href="kids-coading.php">Kid's Coading</a>
                      </li>
                      <li class="menu-item-has-children single-menu">
                        <a href="interview-q.php">Interview Q</a>
                      </li>
                      <li class="menu-item-has-children single-menu">
                        <a href="#">Contact</a>
                      </li>
                    </ul>
                    <!-- //.nav-menu -->
                  </nav>
                </div>
                <!-- //.main-menu -->
                <div class="expand-btn-inner">
                  <ul>
                    <li>
                      <a class="apply-btn" href="#">6 Month Free Tenant Access</a>
                    </li>
                  </ul>
                  <span><a id="nav-expander" class="nav-expander style5">
                      <img src="assets/images/about/24-hour.png" alt="" class="img-fluid"></a></span>
                </div>
              </div>
            </div>
          </div>
          <!-- Menu End -->


        </header>
        <!--Header End-->
      </div>
      <!--Full width header End-->
      <!-- Menu End -->

    </header>
    <!--Header End-->
  </div>